### PR TITLE
Fixed #124

### LINKED ISSUE #124: SQL Updater cannot execute function creations
If you try to execute a patch file (e.g. patch_2.sql), which contains a `CREATE FUNCTION` statement, it does not work. An SQL Syntax Error is thrown. 
When the statement is executed via the command line, it does work perfectly fine.
Neither when running with using other Delimiters, nor without them does work.

Here is the statement I ran into this issue with: [GIST](https://gist.github.com/Simzahn001/d0aa8e14ba69c1e7576ac5c8525838e8)
Setup when the issue first occurred:
 - Database: MariaDB
 - Program, which uses the SADU Updater: A PaperMC plugin executed on MC version 1.19.4; Java version 17
Tested with:
 - Standalone java application on java 17, java 20, java 8
 - Simpler `CREATE FUNCTIONS` with just a simple statement inside
All Tests performed on Server running on Debian 12.0 (Debian 12.1 not tested)

Solution I use for now:
Just remove the `CREATE FUNCTION` statements from the patch file and add them manually xD

### PR DESCRIPTION
**Pull request by Simzahn001**
- Added the class StatementSplitter.java, which has is capable of splitting Statements at the regex as well as taking delimiters into account. Added methods to specify the standard used splitting regex `;` and change the delimiter, but this is not used in this case.
 - Implemented this improved Splitter into the MariaDb.java wrapper class.
 - Wrote various tests located in StatementSplitterTest.java.

### CODE REVIEW

**Comment by rainbowdashlabs** [comment]
Thank you for the PR. I like the approach, but I think we should make it a bit more restrictive and simplify it.

I am not really a friend of removing all line breaks from the patch, since this kind of makes it unreadable for debugging,

I would suggest the following change to simplify the logic and make it easier to understand.

1. Keep line breaks.
2. Iterate over each line
3. If a line starts with DELIMITER use the following chars as the new delimiter.
4. If a line ends with the currently assigned delimiter it is meant to end the statement.

That way we only have to check for a contains in a line and the line end instead of iterating about the whole file.
That should be much faster and simpler as well.

It also removed the risk of the delimiter used in a string expression inside the statement and breaking the statement by this since it wont be at the end of the line.

With that is might also be possible to move this into a utility class and a static method to get rid of the object creation.

This splitter should be implemented for prob every database beside Postgres which allows execution of multiple statements by default.

**Comment by Simzahn001** [comment]
I agree with you in the point that we should take this into a utility class and a static context.

Regarding the simplification: I think it isn't a good choise to only look for the delimiter statement at the beginning or end of each line, because many devs (at least the ones I know xD) tend to write oneliners of SQL statements. This may lead to an unexpected behavior, where it is not easy to ensure that the devs, using SADU, know about this issue (At least I think often, if something has a weired behavior: "why didn't they just fix it, so I don't have to mind this issue?").

Further I don't think that the performance issue is a big thing. The Updater is only executed at startup and not repeatedly during the execution of a running process.

The little bit of performance is in my opinion definitely worth the more consistency and intuitiveness we get from this approach, don't you think so?

**Comment by Simzahn001** [comment]
I agree with you in the point that we should take this into a utility class and a static context.

Regarding the simplification: I think it isn't a good choise to only look for the delimiter statement at the beginning or end of each line, because many devs (at least the ones I know xD) tend to write oneliners of SQL statements. This may lead to an unexpected behavior, where it is not easy to ensure that the devs, using SADU, know about this issue (At least I think often, if something has a weired behavior: "why didn't they just fix it, so I don't have to mind this issue?").

Further I don't think that the performance issue is a big thing. The Updater is only executed at startup and not repeatedly during the execution of a running process.

The little bit of performance is in my opinion definetly worth the more consistency and intuitiveness we get from this approach, don't you think so?

**Comment by Simzahn001** [comment]
Hmm somehow I cannot push any commited changes into this branch... "invalid access rights"
Gonna work that out tomorrow :)

**Comment by rainbowdashlabs** [comment]
> many devs (at least the ones I know xD) tend to write oneliners of SQL statements

I would consider this a very bad practice for readability on bonk them. But yes I get your point.

Could we at least preserve line breaks then? This shouldnt interfere with your current implementation anyway. Just remove the replace, which would break anyway on windows and mac line ending atm.

**Comment by Simzahn001** [comment]
Keeping the linebreaks is a good idea, debugging would be painful otherwise. 👍

**Comment by Simzahn001** [comment]
I've implmemented the static stuff already, gonna commit a solution to preserve the linebreaks today.

**Comment by Simzahn001** [comment]
Okey, I've just tried to resolve the issue with the whitespaces and indentions, but as it turns out, they are already preserved :). I've also testet it quickly:
image (Please don't blame me for my quick sysout, it's not gonna stay there xD)

I have removed the the whitespaces at the Test Class, that's true [StatementSplitterTest.java Line 102ff](https://github.com/Simzahn001/sadu/blob/f2aae59213ffcfc3ff2db93158dd439de446ed57/sadu-mariadb/src/test/java/de/chojo/sadu/databases/StatementSplitterTest.java#L102C64-L102C64). This is only to avoid complications with the assert, because this kind of issue would not affect the function (just the estatic ;) ).

**Comment by Simzahn001** [comment]
Okey, I've just tried to resolve the issue with the whitespaces and indentions, but as it turns out, they are already preseved :). I've also testet it quickly:
image (Please don't blame me for my quick sysout, it's not gonna stay there xD)

I have removed the the whitespaces at the Test Class, that's true [StatementSplitterTest.java Line 102ff](https://github.com/Simzahn001/sadu/blob/f2aae59213ffcfc3ff2db93158dd439de446ed57/sadu-mariadb/src/test/java/de/chojo/sadu/databases/StatementSplitterTest.java#L102C64-L102C64). This is only to avoid complications with the assert, because this kind of issue would not affect the function (just the estatic ;) ).


However, I've included a small improvement. [Read Commit](https://github.com/rainbowdashlabs/sadu/pull/127/commits/d2689ed9af223118ab30f80962233f5399d8624d) Now it looks completely like before: 
image

**Comment by rainbowdashlabs** [comment]
Thank you for the changes c:
I just found one small thing I need to clear up. I will test it myself if you do not have the time, but would something like this be escaped?

```sql
QUERY;
QUERY WITH DELIMITER;
DELIMITER //
QUERY // 
DELIMITER ;
QUERY;
```
`QUERY WITH DELIMITER;` should not be splitted since the DELIMITER keyword is not used after the delimiter character sequence. Is that the case already, or do we need to do something about this?

That way even using the word delimiter in queries or table definition wouldnt cause issues and will make it more save. We cant risk to break some patch scripts by people using the delimiter word in their queries. I would like to make this the default, so we need to be careful.

**Comment by rainbowdashlabs** [comment]
Sorry, but I found two more small issues.

1. The delimiter at the end of the query needs to be either removed or replaced with `;` in any case otherwise queries like `SELECT delimiter FROM table2 //` would cause a database error.
2. The DELIMITER change statements need to be completely stripped from the split statements since those are in no way valid SQL

**Comment by Simzahn001** [comment]
Could you please explain it more detailed, I don't understand what you mean .-.

**Comment by rainbowdashlabs** [comment]
splitStatements is supposed to yield an array of executable queries to send to the database. That means that everything that will cause errors needs to be stripped away. This includes used delimiters that are not ; and the statements to change the delimiter

```
QUERY;
QUERY WITH DELIMITER;
DELIMITER // -- Error because this is not an sql query
QUERY //  -- Error because // is not recognized by sql
DELIMITER ; -- Error because this is not an sql query
QUERY;
```
The first and second query is fine.
The third "query" needs to be removed from the array because it is just there to change our internal delimiter and is not part of the upgrade script.
The fourth query will fail because `//` is still there as a delimiter, but is not an sql delimiter to end the statement. SQL will simply throw an error because it cant interpret `//`. We need to either remove the delimiter where we split or replace any delimiter with `;`
The fifth is again our internal delimiter change which is again not valid and needs to be removed

**Comment by Simzahn001** [comment]
So, the delimiter statements should be combined with the statements between then?
Like this?
`QUERY;
-- Split here
QUERY WITH DELIMITER;
-- Split here
DELIMITER //
QUERY //
DELIMITER ;
-- Split here
QUERY;`

**Comment by rainbowdashlabs** [comment]
I am not sure we are on the same page.

```sql
QUERY;
QUERY WITH DELIMITER;
DELIMITER // -- Error because this is not an sql query
QUERY //  -- Error because // is not recognized by sql
DELIMITER ; -- Error because this is not an sql query
QUERY;
```

Throwing this code into the splitStatement method yields this result:
```
"QUERY;"
"QUERY WITH DELIMITER;"
"QUERY ;" # Note that // was replaced with ;
"QUERY;"
```

**Comment by Simzahn001** [comment]
Hmm, If I run the statement you gave as example, the output is following:
image
This is correct, isn't it?

**Comment by rainbowdashlabs** [comment]
No it **should** yield this array
```java
["CREATE TABLE...;",
"CREATE TABLE delimiter AS...;",
"CREATE FUNCTION... ;", // Note that // was replaced with ;
"CREATE TABLE...;"]```
but it doesnt.

**Comment by Simzahn001** [comment]
Okey, I think I did fix it.

This is an example of how the statements are split now.
The SQL statement before the splitting:
`        final String sql = """
                SELECT * FROM delimiter;
                DELIMITER //
                SELECT test FROM table2 //
                SELECT test FROM table //
                DELIMITER ;
                SELECT * FROM 'delimiter';
                """;`
Afterwards:
image


I think this should work out ;)

**Comment by rainbowdashlabs** [comment]
@Simzahn001 The delimiter was still contained inside the sql statements.
I had some time, so I adjusted your split method and kind of ended up with an own shorter implementation, sorry for that. 
However it works now and all your tests pass as well after adjusting them a bit. Have a look at it. Maybe you understand the issue that it had.

**Review by rainbowdashlabs — APPROVED** [review]

**Pull request merged**
